name = "cf-worker-ai"
main = "src/index.js"
compatibility_date = "2023-10-02"
send_metrics = false

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id = "19764baa-24dd-4380-b7da-e3c9891dbf92"

[[queues.producers]]
queue = "embeddings"
binding = "EMBEDDINGS_QUEUE"

[[queues.consumers]]
queue = "embeddings"
max_batch_size = 1
# max_batch_timeout = 30

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# [vars]
# MY_VARIABLE = "production_value"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/workers/platform/services
# [[services]]
# binding = "MY_SERVICE"
# service = "/api/*"
